# ==========================================
# BANCO DE DADOS
# ==========================================

spring.datasource.url=jdbc:mysql://localhost:3306/db_avaliacao_psicossocial
spring.datasource.username=root
spring.datasource.password=

# ==========================================
# JPA
# ==========================================

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

# ==========================================
# LOGS
# ==========================================

logging.level.root=WARN

# Spring Boot / aplicação
logging.level.org.springframework.boot=INFO

# Tomcat
logging.level.org.springframework.boot.web.embedded.tomcat=INFO

# Hikari - conexão com banco
logging.level.com.zaxxer.hikari=INFO

# Hibernate
logging.level.org.hibernate=ERROR